jobs:
  build:
    defaults:
      run:
        working-directory: codes/go/
    name: Go ${{ matrix.go-version }} on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup Go ${{ matrix.go-version }}
      uses: actions/setup-go@v3
      with:
        go-version: ${{ matrix.go-version }}
    - continue-on-error: true
      name: Check out code into the Go module directory
      run: go get -v -t -d ./...
    - continue-on-error: true
      name: Build
      run: go build -v ./...
    - continue-on-error: true
      name: Test with Go
      run: go test -v ./...
    strategy:
      matrix:
        go-version:
        - 1.19.x
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Go
on:
  repository_dispatch:
    types: trigger-ga___go.yml
