jobs:
  build:
    name: Java ${{ matrix.Java }} sample
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Setup java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: ${{ matrix.java }}
    - continue-on-error: true
      run: javac -d codes/java/build codes/java/**/*.java
    strategy:
      matrix:
        java:
        - '11'
        - '17'
name: Java
on:
  repository_dispatch:
    types: trigger-ga___java.yml
