jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - continue-on-error: true
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.x
    - continue-on-error: true
      name: Run JavaScript Code
      run: deno run -A codes/javascript/test_all.js
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: JavaScript
on:
  repository_dispatch:
    types: trigger-ga___javascript.yml
