jobs:
  build:
    name: Kotlin on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4.1.2
    - continue-on-error: true
      name: Build JAR
      run: kotlinc codes/kotlin/**/*.kt -include-runtime -d codes/kotlin/build/test.jar
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
name: Kotlin
on:
  repository_dispatch:
    types: trigger-ga___kotlin.yml
