jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: brndnmtthws/rust-action-rustup@v1
      with:
        toolchain: nightly
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build
      run: cargo build --manifest-path=codes/rust/Cargo.toml && cargo build --manifest-path=codes/rust/Cargo.toml
        --release
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: Rust
on:
  repository_dispatch:
    types: trigger-ga___rust.yml
