jobs:
  build:
    name: Swift on ${{ matrix.os }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      name: Build
      run: swift build --package-path codes/swift
    strategy:
      matrix:
        os:
        - ubuntu-22.04
        - macos-14
name: Swift
on:
  repository_dispatch:
    types: trigger-ga___swift.yml
