jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
    - continue-on-error: true
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
    - continue-on-error: true
      name: Install dependencies
      run: cd codes/typescript && npm install
    - continue-on-error: true
      name: Check TypeScript code
      run: cd codes/typescript && npm run check
    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest
name: TypeScript
on:
  repository_dispatch:
    types: trigger-ga___typescript.yml
